### ISSUE TITLE
Execution of ServiceCallout SCO-AddURLVault failed

### ISSUE THREAD

**Issue by edwinsmasher** [bnjunge/MPESA-API-Tutorial#2]
Hello Am getting the following error when i try to register my urls. Please help

{"Envelope":{"encodingStyle":"http:\/\/schemas.xmlsoap.org\/soap\/encoding\/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SCO-AddURLVault failed. Reason: ResponseCode 409 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}{"Envelope":{"encodingStyle":"http:\/\/schemas.xmlsoap.org\/soap\/encoding\/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SCO-AddURLVault failed. Reason: ResponseCode 409 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}

**Comment by wmandai** [comment]
> Hello Am getting the following error when i try to register my urls. Please help
> 
> {"Envelope":{"encodingStyle":"http://schemas.xmlsoap.org/soap/encoding/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SCO-AddURLVault failed. Reason: ResponseCode 409 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}{"Envelope":{"encodingStyle":"http://schemas.xmlsoap.org/soap/encoding/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SCO-AddURLVault failed. Reason: ResponseCode 409 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}

Try using Shortcode 1 in Test Credentials

**Comment by intrprince1** [comment]
Change your shortcode to 600730

**Comment by madhums** [comment]
Why do some short codes work and some don't? I can't find any explanation for this inconsistent behaviour.

**Comment by mktowett** [comment]
I also changed shortcode to 600730 and it work.

**Comment by vomondi154** [comment]
Thanks. I changed it to 600730 and it worked too. Is there an explanation for the inconsistency?

**Comment by PatrickNthiwa** [comment]
Hi i have been tryimg to write a script for c2b but i get a similar error code i,e

### {"Envelope":{"encodingStyle":"http:\/\/schemas.xmlsoap.org\/soap\/encoding\/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SC-SearchURL failed. Reason: ResponseCode 503 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}{"Envelope":{"encodingStyle":"http:\/\/schemas.xmlsoap.org\/soap\/encoding\/","Body":{"Fault":{"faultcode":"soap:Server","faultstring":"Execution of ServiceCallout SC-SearchURL failed. Reason: ResponseCode 503 is treated as error","faultactor":{},"detail":{"source":{"errorcode":"steps.servicecallout.ExecutionFailed"}}}}}}


##what can i do to solve the problem because i have tried to use the shortcode mentioned ealier but still the error is there!
